In [1]:
#Create a numpy array of size 10, filled with zeros
import numpy as np

zeros_array = np.zeros(10)

print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
#Create a numpy array with values ranging from 10 to 49 and set its datatype to float

float_array = np.arange(10, 50, dtype=float)

print(float_array)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


In [3]:
#Create a numpy matrix of 2*2 integers, filled with ones.

ones_matrix = np.ones((2, 2), dtype=int)

print(ones_matrix)

[[1 1]
 [1 1]]


In [4]:
#Create a numpy matrix of 3*2 float numbers, filled with ones.

ones_matrix_float = np.ones((3, 2), dtype=float)

print(ones_matrix_float)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
#Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones. 

X = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a new array with the same shape and type as X, filled with ones
ones_like_X = np.ones_like(X)

print(ones_like_X)


[[1 1 1]
 [1 1 1]]


In [6]:
#Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros. (hint: similar function as above exists for zeros as well)
# Given matrix X
X = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a new matrix with the same shape and type as X, filled with zeros
zeros_like_X = np.zeros_like(X)

print(zeros_like_X)

[[0 0 0]
 [0 0 0]]


In [7]:
#Create a numpy matrix of 4*4 integers, filled with fives.

# Create a 4x4 NumPy matrix filled with fives
matrix_of_fives = np.full((4, 4), 5, dtype=int)

print(matrix_of_fives)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [8]:
#Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

# Given matrix X
X = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a new matrix with the same shape and type as X, filled with sevens
sevens_like_X = np.full_like(X, 7)

print(sevens_like_X)

[[7 7 7]
 [7 7 7]]


In [9]:
#Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

identity_matrix = np.eye(3, dtype=int)

print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [10]:
#Create a numpy array, filled with 3 random integer values between 1 and 10.

random_array = np.random.randint(1, 11, size=3)

print(random_array)

[ 7  9 10]


In [11]:
#Create a 3*3*3 numpy matrix, filled with random float values.

random_float_matrix = np.random.rand(3, 3, 3)

print(random_float_matrix)

[[[0.78318093 0.18726529 0.99509237]
  [0.67365681 0.97565035 0.98789296]
  [0.19625348 0.03911592 0.35768031]]

 [[0.9608466  0.00327227 0.90997599]
  [0.04493533 0.62496737 0.36297871]
  [0.5423832  0.33764223 0.38048142]]

 [[0.60832974 0.47909951 0.76337536]
  [0.45385577 0.04021211 0.66011349]
  [0.3467757  0.15990353 0.67274316]]]


In [12]:
#Create a numpy array with numbers from 1 to 10

array_from_1_to_10 = np.arange(1, 11)

print(array_from_1_to_10)


[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
#Create a numpy array with the odd numbers between 1 to 10

odd_numbers_array = np.arange(1, 11, step=2)

print(odd_numbers_array)

[1 3 5 7 9]


In [14]:
#Create a numpy array with numbers from 1 to 10, in descending order.

descending_array = np.arange(10, 0, -1)

print(descending_array)

[10  9  8  7  6  5  4  3  2  1]


In [15]:
#Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

matrix_0_to_8 = np.arange(9).reshape(3, 3)

print(matrix_0_to_8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
# Array indexing:

# Given the X numpy array, show its first element

X = np.array(['A','B','C','D','E'])

first_element = X[0]

print(first_element)


A


In [17]:
#Given the X numpy array, show its last element

X = np.array(['A','B','C','D','E'])

last_element = X[-1]

print(last_element)

E


In [18]:
#Given the X numpy array, show its first three elements

X = np.array(['A','B','C','D','E'])

first_three_elements = X[:3]

print(first_three_elements)

['A' 'B' 'C']


In [19]:
#Given the X numpy array, show all middle elements

X = np.array(['A','B','C','D','E'])

length = len(X)

if length % 2 == 0:
    # If the length is even, there are two middle elements
    middle_elements = X[length // 2 - 1 : length // 2 + 1]
else:
    # If the length is odd, there is a single middle element
    middle_elements = X[length // 2]

print(middle_elements)

C


In [20]:
#Given the X numpy array, show the elements in reverse position.

X = np.array(['A','B','C','D','E'])

reverse_elements = X[::-1]

print(reverse_elements)

['E' 'D' 'C' 'B' 'A']


In [21]:
#Given the X numpy array, show the elements in an odd position.

X = np.array(['A','B','C','D','E'])

odd_position_elements = X[::2]

print(odd_position_elements)

['A' 'C' 'E']


In [22]:
#Given the X numpy matrix, show the first row’s elements.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

first_row_elements = X[0, :]

print(first_row_elements)

[1 2 3 4]


In [23]:
#Given the X numpy matrix, show the last row elements.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

last_row_elements = X[-1, :]

print(last_row_elements)

[13 14 15 16]


In [24]:
#Given the X numpy matrix, show the first element on first row

X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

first_element_first_row = X[0, 0]

print(first_element_first_row)

1


In [25]:
# Given the X numpy matrix, show the last element on last row.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

last_element_last_row = X[-1, -1]

print(last_element_last_row)

16


In [26]:
# Given the X numpy matrix, show the first two elements on the first two rows.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

first_two_elements_first_two_rows = X[:2, :2]

print(first_two_elements_first_two_rows)

[[1 2]
 [5 6]]


In [27]:
# Given the X numpy matrix, show the last two elements on the last two rows

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

last_two_elements_last_two_rows = X[-2:, -2:]

print(last_two_elements_last_two_rows)

[[11 12]
 [15 16]]


In [28]:
# Array manipulation

# Convert the given integer numpy array to float (you need to google the function that will help you do this)

X = [-5, -3, 0, 10, 40]

X_float = np.array(X, dtype=float)

print(X_float)


[-5. -3.  0. 10. 40.]


In [29]:
# Reverse the given numpy array (first element becomes last) through indexing

X = [-5, -3, 0, 10, 40]

reversed_X = X[::-1]

print(reversed_X)

[40, 10, 0, -3, -5]


In [30]:
# Given the X numpy array, set the fifth element equal to 1

X = np.zeros(10)

X[4] = 1

print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [31]:
# Given the X numpy matrix, change the last row with all 1

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, :] = 1

print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


In [32]:
# Given the X numpy matrix, add 5 to every element

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X_plus_5 = X + 5

print(X_plus_5)

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
